### ISSUE TITLE
All calls resulting in 410

### ISSUE THREAD

**Issue by aguywithanidea** [jugend/amazon-ecs#71]
All calls documented in the README result in this:

```
Traceback (most recent call last):
       10: from script/rails:6:in `<main>'
        9: from script/rails:6:in `require'
        8: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        7: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        6: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        5: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
        4: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
        3: from (irb):16
        2: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/amazon-ecs-2.5.0/lib/amazon/ecs.rb:102:in `item_search'
        1: from /Users/pifmag/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/amazon-ecs-2.5.0/lib/amazon/ecs.rb:146:in `send_request'
Amazon::RequestError (HTTP Response: 410 Gone)**
```

**Comment by dkam** [comment]
You need to migrate to the new API - you can use the either of these gems : https://github.com/dkam/paapi or https://github.com/hakanensari/vacuum
